def get_machine_batch(t):

    machine_batch = {
    'o1' : ('old'),
    'o2' : ('old'),
    'o3' : ('old'),
    'o4' : ('old'),
    'o5' : ('old'),
    'o6' : ('old'),
    'o7' : ('old'),
    'o8' : ('old'),
    'o9' : ('old'),
    'o10' : ('old'),
    'n1' : ('new'),
    'n2' : ('new'),
    'n3' : ('new'),
    'n4' : ('new'),
    'n5' : ('new'),
    'n6' : ('new'),
    'n7' : ('new'),
    'n8' : ('new'),
    'n9' : ('new'),
    'n10' : ('new'),
    'n11' : ('new'),
    'n12' : ('new'),
    'n13' : ('new'),
    'n14' : ('new'),
    'n15' : ('new'),
    'n16' : ('new'),
    'n17' : ('new'),
    'n18' : ('new'),
    'n19' : ('new'),
    'n20' : ('new'),
    }
    return machine_batch[t]
